
etl:
  outputs:
    dev:
      account: your-account-identifier
      database: your_db
      password: your-password
      role: your_role
      schema: your_schema
      threads: 10
      type: snowflake
      user: your-username
      warehouse: your_wh
  target: dev
