[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "data-tools"
version = "0.1.0"
description = "A library for data processing tools."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "Apache-2.0" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pandas>=2.3.1",
    "pydantic>=2.11.7",
]

[dependency-groups]
test = ["pytest"]
lint = ["ruff"]

[tool.ruff]
src = ["src"]

[tool.setuptools.packages.find]
where = ["src"]
