# src/intugle/conceptual_search/models.py
from typing import List, Optional

from pydantic import BaseModel, Field


class ConceptualAttribute(BaseModel):
    """An abstract attribute for the desired data product."""
    name: str = Field(description="A business-friendly name for the column, e.g., 'Patient Age'")
    description: str = Field(description="A detailed explanation of what this attribute represents.")
    logic: str = Field(description="A natural language description of the calculation, e.g., 'Calculate the age based on the date of birth'")


class ConceptualPlan(BaseModel):
    """The conceptual plan generated by Agent 1, which can be reviewed by the user."""
    attributes: List[ConceptualAttribute]

    def to_dict(self):
        return self.model_dump()


class MappedAttribute(ConceptualAttribute):
    """A conceptual attribute that has been mapped to a physical column."""
    column_id: str = Field(description="The fully qualified column ID from the semantic layer, e.g., 'patients.birth_date'")
    measure_func: Optional[str] = Field(default=None, description="The aggregation function if any, e.g., 'COUNT', 'SUM'")


class MappedPlan(BaseModel):
    """The final plan after Agent 2 has mapped attributes to columns."""
    attributes: List[MappedAttribute]
