name: Vale Lint Checker

on:
  push:
    branches:
      - main
    paths:
      - 'docsite/**'
  pull_request:
    branches:
      - '*'
    paths:
      - 'docsite/**'
  workflow_dispatch:

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Install Vale (safe, no sudo needed)
      - name: Install Vale
        run: |
          curl -fsSL https://github.com/errata-ai/vale/releases/latest/download/vale_Linux_64-bit.tar.gz -o vale.tar.gz
          tar -xzf vale.tar.gz
          echo "$PWD" >> $GITHUB_PATH

      # Run Vale using config inside docsite/
      - name: Run Vale Lint
        run: vale --config=docsite/.vale.ini docsite/
